name: seven
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  carousel_slider: ^4.2.1
  connectivity: ^3.0.6
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.1
  firebase_core: ^2.15.0
  firebase_core_platform_interface: ^4.8.0
  firebase_messaging: ^14.6.5
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^9.0.0
  flutter_localization: ^0.1.13
  flutter_typeahead: ^4.6.2
  flutter_widget_from_html_core: ^0.10.3
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.2
  http: ^0.13.0
  image_picker: ^0.8.4+8
  path: ^1.8.3
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer_animation: ^2.0.0
  universal_html: ^2.2.3
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.12
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
