// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhc6O2Q2dC1KOswwr5ZFn8iNZUMOQuzg',
    appId: '1:125671047038:web:5c23c40defc27ab8b27d2f',
    messagingSenderId: '125671047038',
    projectId: 'seven-7-app',
    authDomain: 'seven-7-app.firebaseapp.com',
    storageBucket: 'seven-7-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLZGy2PBbNE3eKA25xIyA0ZGAsSpREiQ',
    appId: '1:125671047038:android:667c64952aff2237b27d2f',
    messagingSenderId: '125671047038',
    projectId: 'seven-7-app',
    storageBucket: 'seven-7-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgXUS15XROFDVV2ecPKEo_nTOwIKSRd34',
    appId: '1:125671047038:ios:ca9bd21ca7f683f4b27d2f',
    messagingSenderId: '125671047038',
    projectId: 'seven-7-app',
    storageBucket: 'seven-7-app.appspot.com',
    iosClientId: '125671047038-6up6tft403o4pbf5364iv2cic5bg0tp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.seven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgXUS15XROFDVV2ecPKEo_nTOwIKSRd34',
    appId: '1:125671047038:ios:3ffd7ee992f2c9ceb27d2f',
    messagingSenderId: '125671047038',
    projectId: 'seven-7-app',
    storageBucket: 'seven-7-app.appspot.com',
    iosClientId: '125671047038-g44kdkcce97ip960itao7moqjpki92t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.seven.RunnerTests',
  );
}
